### ISSUE TITLE
[Vulnerability] Kokeepcha API key leaked in `main.py`

### ISSUE THREAD

**Issue by uhidontkno** [AG-597/AG-Promo-Gen#1]
Hardcoding API keys into your code is bad practice. Store your Kokeepcha API key in an environment variable or use a file and exclude it using `.gitignore`

**Comment by AG-597** [comment]
The API key is not valid I ensured I did not leak anything before posting, thanks for the info.

**Comment by AG-597** [comment]
Resolved
